Working through code review stuff editor/arbmark -> api/extmark char_u  -> cstr_t get_tv_string and get_tv_number generating headers moved test to api/
when i remove the coment on line 118 in buffer_defs.h,
i get this.. message when i run `make`

```bash
ninja  -C .deps
ninja: Entering directory `.deps'
[2/2] cd /home/alfa/Documents/git/neovim/.deps && /usr/bin/cmake -E touch .third-party
ninja  -C build
ninja: Entering directory `build'
[6/137] Building C object src/nvim/CMakeFiles/nvim.dir/event/wstream.c.o
FAILED: /usr/bin/cc  -DHAVE_CONFIG_H -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -Wconversion -g -Iconfig -I../src -isystem ../.deps/usr/include -Isrc/nvim/auto -Iinclude    -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -MMD -MT src/nvim/CMakeFiles/nvim.dir/event/wstream.c.o -MF "src/nvim/CMakeFiles/nvim.dir/event/wstream.c.o.d" -o src/nvim/CMakeFiles/nvim.dir/event/wstream.c.o   -c ../src/nvim/event/wstream.c
In file included from ../src/nvim/mark.h:78:0,
                 from ../src/nvim/api/extmark.h:4,
                 from ../src/nvim/buffer_defs.h:118,
                 from ../src/nvim/normal.h:6,
                 from ../src/nvim/ex_cmds_defs.h:8,
                 from ../src/nvim/message.h:7,
                 from ../src/nvim/vim.h:266,
                 from ../src/nvim/event/wstream.c:10:
include/mark.h.generated.h:23:15: error: unknown type name ‘exarg_T’
 void do_marks(exarg_T *eap);
               ^
include/mark.h.generated.h:24:18: error: unknown type name ‘exarg_T’
 void ex_delmarks(exarg_T *eap);
```